spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elasticsearch
    username: san
    password: password
    
  cache:
    type: redis
    #host: redis7alpine_redis_1
    #port: 6379
    redis:
      #time-to-live: 60000
      enable-statistics: true
      
  data:
    redis:
      client-name: redis7alpine_redis_1
      password: password
      #client-type:
      
  jpa:
    hibernate:
      ddl-auto: update
