spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elasticsearch
    username: root
    password: secret
  data:
    elasticsearch:
      cluster-name: elastic
      cluster-nodes: localhost:9300