server:
  port: 8080
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://localhost:9090
          predicates:
            - Path=/user/**
        - id: PORTAL-SERVICE
          uri: lb://localhost:9091
          predicates:
            - Path=/portal/**       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
