services:
  postgres:
    image: 'postgres:16'
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1
    environment:
      - 'POSTGRES_DB=posts'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
